version: '3.8'

services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI

  minio:
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console UI

  # Monitoring profile is optional, uncomment to map ports if you run with --profile monitoring
  # prometheus:
  #   ports:
  #     - "9090:9090"
  # grafana:
  #   ports:
  #     - "3000:3000"
